### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Scenicslayer** [Hoizame/AtlasLootClassic#412]
**AtlasLoot version** AtlasLootClassic-v3.1.3.zip Game Version 3.4.2

**Lua error** 

Message: Interface/AddOns/AtlasLootClassic/Data/Companion.lua:674: table index is nil
Time: Sat Oct 14 18:03:35 2023
Count: 1
Stack: Interface/AddOns/AtlasLootClassic/Data/Companion.lua:674: table index is nil
[string "@Interface/AddOns/AtlasLootClassic/Data/Companion.lua"]:674: in function <Interface/AddOns/AtlasLootClassic/Data/Companion.lua:669>
[string "@Interface/AddOns/AtlasLootClassic/Data/Companion.lua"]:682: in function <Interface/AddOns/AtlasLootClassic/Data/Companion.lua:677>
[string "@Interface/AddOns/AtlasLootClassic/Data/Companion.lua"]:689: in function `func'
[string "@Interface/AddOns/AtlasLootClassic/AtlasLoot.lua"]:42: in function <Interface/AddOns/AtlasLootClassic/AtlasLoot.lua:34>

Locals: typ = "MOUNT"
(for index) = 1
(for limit) = 21
(for step) = 1
i = 1
creatureID = nil
(*temporary) = <table> {
 23909 = true
 33226 = true
}
(*temporary) = 1
(*temporary) = "table index is nil"
COLLECTED_COMPANIONS = <table> {
 23909 = true
 33226 = true
}

Message: Interface/AddOns/AtlasLootClassic/Data/Companion.lua:674: table index is nil
Time: Sat Oct 14 18:10:14 2023
Count: 289
Stack: Interface/AddOns/AtlasLootClassic/Data/Companion.lua:674: table index is nil
[string "@Interface/AddOns/AtlasLootClassic/Data/Companion.lua"]:674: in function <Interface/AddOns/AtlasLootClassic/Data/Companion.lua:669>
[string "@Interface/AddOns/AtlasLootClassic/Data/Companion.lua"]:682: in function <Interface/AddOns/AtlasLootClassic/Data/Companion.lua:677>

Locals: typ = "MOUNT"
(for index) = 1
(for limit) = 21
(for step) = 1
i = 1
creatureID = nil
(*temporary) = <table> {
 23909 = true
 33226 = true
}
(*temporary) = 1
(*temporary) = "table index is nil"
COLLECTED_COMPANIONS = <table> {
 23909 = true
 33226 = true
}

**Describe the bug** Lua Error appears all the time, no matter what I do or disable

**To Reproduce** Addon loaded, logging in, no actions taken to reproduce

**Expected behavior** Lua Error appears on screen at all times unless I completely disable addon features(all of them)

**Screenshots**

**Additional context**

**Comment by bisforboman** [comment]
Seems like the error originates at:
`local creatureID = GetCompanionInfo(typ, i)`

Where creatureID becomes `nil`. 

I inserted a row after this one: 
`if creatureID == nil then break end`

Which atleast prevents the error for me.

**Comment by Fbspammer** [comment]
[Fixed Version](https://github.com/Anyalah/AtlasLootClassic/releases/tag/v3.4.3.pre-release)

**Comment by roeleert** [comment]
> [Fixed Version](https://github.com/Anyalah/AtlasLootClassic/releases/tag/v3.4.3.pre-release)

this does not fix the above problem, you cannot make a list of items now without atltasloot failing. Once you add an item, atlasloot stops functioning untill you remove the item from the list

**Comment by Scenicslayer** [comment]
Fixed Version fixed the issue I was having, I am currently not experiencing any other errors at this time, thank you :)

**Comment by Daevert** [comment]
The function GetNumCompanions(typ) returns nil when typ is "MOUNT". This was changed in WoW 3.4.3. These functions are used instead to retrieve mount information:

[[C_MountJournal.GetMountIDs](https://warcraft.wiki.gg/wiki/API_C_MountJournal.GetMountIDs)]
[[C_MountJournal.GetDisplayedMountInfo](https://warcraft.wiki.gg/wiki/API_C_MountJournal.GetDisplayedMountInfo)]
